# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    permissions:
      contents: write
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Build Release
        run: cargo build --release --target stable-x86_64-pc-windows-msvc
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/iso8583_parser.exe          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
